
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace EasyCardSystem.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmpData
{

    public string EmpID { get; set; }

    public string EmpCardCode { get; set; }

    public string EmpDept { get; set; }

    public string EmpPwd { get; set; }

    public string EmpName { get; set; }

    public string Email { get; set; }

    public string EmpState { get; set; }

    public string Role { get; set; }

    public string EmpDisable { get; set; }

}

}
